### ISSUE TITLE
Issues building on Windows

### ISSUE THREAD

**Issue by waynegeorge** [mimblewimble/grin-gui#88]
![image](https://github.com/mimblewimble/grin-gui/assets/22817833/4930e14e-5950-4dd0-a210-ea9ac737b5e4)

Just seeing if I could get any help with this build issue. I have rustc 1.76.0 installed and LLVM 17.0.1 on Windows 10 64x. Thanks.

**Comment by yeastplume** [comment]
Github auto-closed this, can you check with the latest, it should work.

**Comment by waynegeorge** [comment]
Yes this builds now. Thanks a lot!
